- name: EC2 Resize from CR Description
  hosts: localhost
  gather_facts: no

  vars:
    snow_host: "https://nowlearning-nlinst04341393-5edtd-0001.lab.service-now.com"
    snow_user: "admin"
    snow_pass: "1S7pw9P5mhrp"
    change_sys_id: "37d3a4d7d9e103107f44c63f4a8f0be3"
    region: "us-east-1"

  tasks:

    - name: Get Change Request
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ snow_host }}"
          username: "{{ snow_user }}"
          password: "{{ snow_pass }}"
        sys_id: "{{ change_sys_id }}"
      register: cr_data

    - name: Extract description
      set_fact:
        desc: "{{ cr_data.records[0].short_description }}"

    - name: Parse values
      set_fact:
        instance_id: "{{ desc.split(' ')[3] }}"
        target_type: "{{ desc.split(' to ')[1] }}"

    - name: Stop EC2
      amazon.aws.ec2_instance:
        instance_ids: ["{{ instance_id }}"]
        state: stopped
        region: "{{ region }}"
        wait: yes

    - name: Change instance type
      amazon.aws.ec2_instance:
        instance_ids: ["{{ instance_id }}"]
        instance_type: "{{ target_type }}"
        region: "{{ region }}"

    - name: Start EC2
      amazon.aws.ec2_instance:
        instance_ids: ["{{ instance_id }}"]
        state: running
        region: "{{ region }}"
        wait: yes

    - name: Update CR
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_host }}"
          username: "{{ snow_user }}"
          password: "{{ snow_pass }}"
        sys_id: "{{ change_sys_id }}"
        state: "Review"
        description: "Automation SUCCESS"
